## This a a project that ivloves prediting flood suspectibility 

### This is a multiclass prediction using the flood suspectibility as the dependent feature and the rest of the features as the independent feature

#### 1. import data into the jupyter notebook  

#### 2. preprocess data 

#### 3. Analysing data 

#### 4. choosing model

#### 5. Training model

#### 6. Evaluating model

#### 7. parameter Tunning

#### 6. making prediction 

###### import the neccessary libraries

In [2]:
!jupyter nbextension enable --py widgetsnbextension

Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: ok


In [3]:
import os
import pandas as pd
import numpy as np
np.set_printoptions(precision=4)

import catboost 
print(catboost.__version__)

1.0.4


##### importing the data...

## Data description 

In [6]:
dataset = pd.read_excel('Osun Basin- Processed Numerical Values.xlsx')

In [7]:
dataset

Longitude     Latitude  TWI  Soil Type  Slope  Road  River  \
0        594290.5135  711743.7948    3          2      2     5      4   
1        594390.5135  711743.7948    3          2      3     5      4   
2        594490.5135  711743.7948    3          2      2     5      4   
3        594590.5135  711743.7948    3          2      3     5      4   
4        594690.5135  711743.7948    4          2      3     5      4   
...              ...          ...  ...        ...    ...   ...    ...   
1015186  634690.5135  921143.7948    2          2      4     5      4   
1015187  634790.5135  921143.7948    2          2      3     5      4   
1015188  634890.5135  921143.7948    2          2      3     5      4   
1015189  634990.5135  921143.7948    2          2      3     5      4   
1015190  635090.5135  921143.7948    2          2      3     5      4   

         Rainfall  NDVI  LULC  DrainageD  DEM  Flood Susceptibility  
0               4     3     3          1    5                     3  
1               4     3     3          1    5                     3  
2               4     3     3          1    5                     3  
3               4     3     3          1    5                     3  
4               4     3     3          1    5                     4  
...           ...   ...   ...        ...  ...                   ...  
1015186         1     2     2          1    2                     2  
1015187         1     1     2          1    2                     2  
1015188         1     1     2          1    2                     2  
1015189         1     1     2          1    2                     2  
1015190         1     1     2          1    2                     2  

[1015191 rows x 13 columns]

In [8]:
# Number of row
'number of rows: {}'.format(len(dataset))

'number of rows: 1015191'

In [9]:
# number of columns
'number of features: {}'.format(len(dataset.columns))

'number of features: 13'

In [10]:
features = dataset.columns

In [11]:
features

Index(['Longitude', 'Latitude', 'TWI', 'Soil Type', 'Slope', 'Road', 'River',
       'Rainfall', 'NDVI', 'LULC', 'DrainageD', 'DEM', 'Flood Susceptibility'],
      dtype='object')

In [12]:

dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1015191 entries, 0 to 1015190
Data columns (total 13 columns):
 #   Column                Non-Null Count    Dtype  
---  ------                --------------    -----  
 0   Longitude             1015191 non-null  float64
 1   Latitude              1015191 non-null  float64
 2   TWI                   1015191 non-null  int64  
 3   Soil Type             1015191 non-null  int64  
 4   Slope                 1015191 non-null  int64  
 5   Road                  1015191 non-null  int64  
 6   River                 1015191 non-null  int64  
 7   Rainfall              1015191 non-null  int64  
 8   NDVI                  1015191 non-null  int64  
 9   LULC                  1015191 non-null  int64  
 10  DrainageD             1015191 non-null  int64  
 11  DEM                   1015191 non-null  int64  
 12  Flood Susceptibility  1015191 non-null  int64  
dtypes: float64(2), int64(11)
memory usage: 100.7 MB


#### No missing value from the data ...

In [13]:
dataset.describe()

Longitude      Latitude           TWI     Soil Type         Slope  \
count  1.015191e+06  1.015191e+06  1.015191e+06  1.015191e+06  1.015191e+06   
mean   6.524653e+05  8.445971e+05  2.716055e+00 -1.496865e+01  2.783500e+00   
std    3.543820e+04  4.825379e+04  5.112248e-01  4.158331e+02  1.049980e+00   
min    5.903905e+05  7.117438e+05  1.000000e+00 -9.999000e+03  1.000000e+00   
25%    6.242905e+05  8.217438e+05  2.000000e+00  1.000000e+00  2.000000e+00   
50%    6.393905e+05  8.585438e+05  3.000000e+00  3.000000e+00  3.000000e+00   
75%    6.808905e+05  8.786438e+05  3.000000e+00  3.000000e+00  4.000000e+00   
max    7.402905e+05  9.211438e+05  4.000000e+00  5.000000e+00  5.000000e+00   

               Road         River      Rainfall          NDVI          LULC  \
count  1.015191e+06  1.015191e+06  1.015191e+06  1.015191e+06  1.015191e+06   
mean   4.363800e+00  3.214045e+00  2.912280e+00  1.060490e+00  2.151458e+00   
std    8.506433e-01  1.264008e+00  1.212308e+00  2.948221e-01  1.066593e+00   
min    1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00   
25%    4.000000e+00  2.000000e+00  2.000000e+00  1.000000e+00  1.000000e+00   
50%    5.000000e+00  4.000000e+00  3.000000e+00  1.000000e+00  2.000000e+00   
75%    5.000000e+00  4.000000e+00  4.000000e+00  1.000000e+00  3.000000e+00   
max    5.000000e+00  5.000000e+00  5.000000e+00  5.000000e+00  5.000000e+00   

          DrainageD           DEM  Flood Susceptibility  
count  1.015191e+06  1.015191e+06          1.015191e+06  
mean   3.195931e+00  3.021261e+00          2.716055e+00  
std    1.219641e+00  1.400526e+00          5.112248e-01  
min    1.000000e+00  1.000000e+00          1.000000e+00  
25%    2.000000e+00  2.000000e+00          2.000000e+00  
50%    3.000000e+00  3.000000e+00          3.000000e+00  
75%    4.000000e+00  4.000000e+00          3.000000e+00  
max    5.000000e+00  5.000000e+00          4.000000e+00

#### we can see from the data that the features are integers, but they look like hashes, if we use it as a numerical data 
#### the model won't perform well so therefore, we will use it as a categorical data. 

#### creating training set and tst set

In [14]:
y = dataset['Flood Susceptibility'] 
X = dataset.drop(['Flood Susceptibility'],axis=1)

In [15]:
X,y

(           Longitude     Latitude  TWI  Soil Type  Slope  Road  River  \
 0        594290.5135  711743.7948    3          2      2     5      4   
 1        594390.5135  711743.7948    3          2      3     5      4   
 2        594490.5135  711743.7948    3          2      2     5      4   
 3        594590.5135  711743.7948    3          2      3     5      4   
 4        594690.5135  711743.7948    4          2      3     5      4   
 ...              ...          ...  ...        ...    ...   ...    ...   
 1015186  634690.5135  921143.7948    2          2      4     5      4   
 1015187  634790.5135  921143.7948    2          2      3     5      4   
 1015188  634890.5135  921143.7948    2          2      3     5      4   
 1015189  634990.5135  921143.7948    2          2      3     5      4   
 1015190  635090.5135  921143.7948    2          2      3     5      4   
 
          Rainfall  NDVI  LULC  DrainageD  DEM  
 0               4     3     3          1    5  
 1          

## splitting dataset

In [16]:
print('labels: {}'.format(set(y)))

labels: {1, 2, 3, 4}


In [17]:
y_unique = y.unique()

In [18]:
#y = [label == y_unique for label in y]

In [19]:
y

0          3
1          3
2          3
3          3
4          4
          ..
1015186    2
1015187    2
1015188    2
1015189    2
1015190    2
Name: Flood Susceptibility, Length: 1015191, dtype: int64

In [20]:
#y = [item.astype(int) for item in y]

#### splitting dataset to training, validation and test set

In [21]:
# import sklearn
from sklearn.model_selection import train_test_split
split_dataset_1= train_test_split(X,y,test_size=0.3,random_state=0)

In [1]:
len(split_dataset_1)

NameError: name 'split_dataset1' is not defined

In [ ]:
X_train,X_val,y_train,y_val = split_dataset_1

In [ ]:
len(X_train)

##### splitting data to validation and test set

In [194]:
from sklearn.model_selection import train_test_split
split_dataset_2 = train_test_split(X_val,y_val,test_size=0.2,random_state=0)

In [197]:
X_val,X_test,y_val,y_test = split_dataset_2

### choosing model...

In [198]:
# import Pool
from catboost import Pool

In [199]:
np.where(X_train.dtypes != np.float64)

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64),)

In [200]:
cat_feature = np.where(X_train.dtypes != np.float64)[0]

In [101]:
cat_feature

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64)

##### making pools...

In [201]:
train_pool = Pool(data = X_train,
                  label = y_train,
                  cat_features= cat_feature)
test_pool = Pool(data = X_val,label = y_val, cat_features=cat_feature)

In [202]:
#y_train

In [203]:
y

0          3
1          3
2          3
3          3
4          4
          ..
1015186    2
1015187    2
1015188    2
1015189    2
1015190    2
Name: Flood Susceptibility, Length: 1015191, dtype: int64

##### importing library and testing with 100 iterations

In [204]:
from catboost import CatBoostClassifier

In [205]:
model = CatBoostClassifier()

In [206]:
model = CatBoostClassifier(iterations=100)
model.fit(X_train,y_train,verbose=10)

Custom logger is already specified. Specify more than one logger at same time is not thread safe.

Learning rate set to 0.5
0:	learn: 0.3413488	total: 410ms	remaining: 40.6s
10:	learn: 0.0018033	total: 3.95s	remaining: 32s
20:	learn: 0.0000301	total: 7.29s	remaining: 27.4s
30:	learn: 0.0000084	total: 10.6s	remaining: 23.6s
40:	learn: 0.0000050	total: 13.9s	remaining: 20.1s
50:	learn: 0.0000036	total: 17.6s	remaining: 16.9s
60:	learn: 0.0000029	total: 21s	remaining: 13.4s
70:	learn: 0.0000023	total: 24.3s	remaining: 9.93s
80:	learn: 0.0000020	total: 27.6s	remaining: 6.48s
90:	learn: 0.0000017	total: 31s	remaining: 3.06s
99:	learn: 0.0000016	total: 34.3s	remaining: 0us


In [209]:
model.best_score_

{'learn': {'MultiClass': 1.5700253661484077e-06}}

### making training and validation  Pool

In [212]:
train_pool = Pool(data = X_train,label = y_train,cat_features=cat_feature)
val_pool = Pool(data=X_val,label=y_val,cat_features=cat_feature)

### selecting objective function and training model

In [220]:
model = CatBoostClassifier(iterations=400,
                           custom_metric=['AUC','Accuracy'],
                           early_stopping_rounds=10,
                           train_dir='flood_pred',
                           use_best_model=True
                    
                          )
                           
model.fit(X=train_pool,eval_set=val_pool,verbose=20,plot=True)

print('model fitted {}'.format(model.is_fitted()))
print('model param: \n{}'.format(model.get_best_iteration()))

Custom logger is already specified. Specify more than one logger at same time is not thread safe.

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Learning rate set to 0.174733
0:	learn: 0.9130651	test: 0.9130789	best: 0.9130789 (0)	total: 6.02s	remaining: 40m 3s
20:	learn: 0.0168842	test: 0.0168750	best: 0.0168750 (20)	total: 2m 28s	remaining: 44m 33s
40:	learn: 0.0005378	test: 0.0005319	best: 0.0005319 (40)	total: 5m 26s	remaining: 47m 38s
60:	learn: 0.0001143	test: 0.0001093	best: 0.0001093 (60)	total: 8m 16s	remaining: 46m
80:	learn: 0.0000599	test: 0.0000564	best: 0.0000564 (80)	total: 11m 9s	remaining: 43m 56s
100:	learn: 0.0000345	test: 0.0000317	best: 0.0000317 (100)	total: 14m 9s	remaining: 41m 56s
120:	learn: 0.0000281	test: 0.0000259	best: 0.0000259 (118)	total: 16m 52s	remaining: 38m 54s
140:	learn: 0.0000165	test: 0.0000147	best: 0.0000147 (139)	total: 19m 46s	remaining: 36m 19s
160:	learn: 0.0000137	test: 0.0000122	best: 0.0000122 (157)	total: 22m 34s	remaining: 33m 30s
Stopped by overfitting detector  (10 iterations wait)

bestTest = 1.045804564e-05
bestIteration = 167

Shrink model to first 168 iterations.
model f

prevented overfitting by using early stopping and using large iteration without initiating a learning rate

##### getting the best score from training and validation data after training ..

In [221]:
model.best_score_

{'learn': {'Accuracy': 1.0, 'MultiClass': 1.182332471195467e-05},
 'validation': {'Accuracy': 1.0,
  'AUC:type=Mu': 1.0,
  'MultiClass': 1.0458045640675782e-05}}

In [292]:
pd.DataFrame(model.best_score_)

learn  validation
Accuracy     1.000000     1.00000
MultiClass   0.000012     0.00001
AUC:type=Mu       NaN     1.00000

In [294]:
model.evals_result_

{'learn': {'Accuracy': [0.999822693288941,
   0.9998241004850605,
   0.999822693288941,
   0.9998255076811801,
   0.9999957784116414,
   0.9999957784116414,
   0.9999957784116414,
   0.999997185607761,
   0.999997185607761,
   0.999997185607761,
   0.999997185607761,
   0.999997185607761,
   0.999997185607761,
   0.9999957784116414,
   0.9999957784116414,
   0.9999957784116414,
   0.9999957784116414,
   0.9999957784116414,
   0.9999957784116414,
   0.9999957784116414,
   0.9999957784116414,
   0.9999957784116414,
   0.9999957784116414,
   0.9999957784116414,
   0.9999957784116414,
   0.9999957784116414,
   0.9999957784116414,
   0.9999957784116414,
   0.9999957784116414,
   0.999997185607761,
   0.999997185607761,
   0.999997185607761,
   0.999997185607761,
   0.999997185607761,
   0.9999985928038805,
   0.9999985928038805,
   0.9999985928038805,
   0.9999985928038805,
   0.9999985928038805,
   0.9999985928038805,
   0.9999985928038805,
   0.9999985928038805,
   1.0,
   1.0,
   1.0,
  

#### checking the numbersof iterations, that is, number of trees 

In [267]:
model.tree_count_

168

##### getting the feature importance 

In [229]:
model.feature_importances_

array([2.2164e+00, 4.2465e+00, 9.2435e+01, 2.2861e-01, 0.0000e+00,
       2.3566e-02, 5.7068e-06, 8.8616e-02, 3.5028e-02, 0.0000e+00,
       3.9602e-01, 3.3021e-01])

#### checking the parameters used in the moel for training...

In [235]:
model.get_all_params()

{'nan_mode': 'Min',
 'eval_metric': 'MultiClass',
 'combinations_ctr': ['Borders:CtrBorderCount=15:CtrBorderType=Uniform:TargetBorderCount=3:TargetBorderType=MinEntropy:Prior=0/1:Prior=0.5/1:Prior=1/1',
  'Counter:CtrBorderCount=15:CtrBorderType=Uniform:Prior=0/1'],
 'iterations': 400,
 'sampling_frequency': 'PerTree',
 'fold_permutation_block': 0,
 'leaf_estimation_method': 'Newton',
 'od_pval': 0,
 'counter_calc_method': 'SkipTest',
 'grow_policy': 'SymmetricTree',
 'penalties_coefficient': 1,
 'boosting_type': 'Plain',
 'model_shrink_mode': 'Constant',
 'feature_border_type': 'GreedyLogSum',
 'ctr_leaf_count_limit': 18446744073709551615,
 'bayesian_matrix_reg': 0.10000000149011612,
 'one_hot_max_size': 2,
 'force_unit_auto_pair_weights': False,
 'l2_leaf_reg': 3,
 'random_strength': 1,
 'od_type': 'Iter',
 'rsm': 1,
 'boost_from_average': False,
 'max_ctr_complexity': 4,
 'model_size_reg': 0.5,
 'simple_ctr': ['Borders:CtrBorderCount=15:CtrBorderType=Uniform:TargetBorderCount=3:Targ

##### checking the paramters manually tunned for  training 

In [236]:
model.get_params()

{'iterations': 400,
 'use_best_model': True,
 'train_dir': 'flood_pred',
 'custom_metric': ['AUC', 'Accuracy'],
 'early_stopping_rounds': 10}

##### checking the important features used in classifying the data...

In [304]:
model.get_feature_importance(train_pool,prettified=True,)

Feature Id  Importances
0         TWI    92.439096
1    Latitude     4.247680
2   Longitude     2.220926
3   DrainageD     0.405760
4         DEM     0.335913
5   Soil Type     0.213966
6    Rainfall     0.081345
7        NDVI     0.031941
8        Road     0.023374
9       Slope     0.000000
10      River     0.000000
11       LULC     0.000000

### loss function change

###### note: for a negative loss function change, it means the feature is not really  good at predictiing the classes , also note that this is not always true when you underfit, probably when you train a model with small iteration.. negative loss change  may fire up saying 'you can do without the the features since you are using small iteration' , increase the itration may later changes the feature with negative loss function to positive 

In [298]:
loss_funct_chg = model.get_feature_importance(train_pool,'LossFunctionChange',prettified=True,)

In [302]:
loss_funct_chg

Feature Id   Importances
0         TWI  1.365704e+00
1   Longitude  3.854690e-06
2    Latitude  3.701130e-06
3         DEM  2.128100e-07
4   DrainageD  1.329843e-07
5    Rainfall  3.125862e-08
6   Soil Type  1.111883e-08
7        NDVI  4.266677e-09
8        Road  3.225949e-09
9       River  1.662160e-10
10      Slope  0.000000e+00
11       LULC  0.000000e+00

###### It was observed from the data that slope and LULC has no effect in the classification of the data.

### making some predictions  with Test Data

In [271]:
pred = model.predict(X_test)
pred

array([[3],
       [3],
       [3],
       ...,
       [4],
       [3],
       [2]], dtype=int64)

### using sklearn to calculate the metrics

In [272]:
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(pred,y_test)

array([[    8,     0,     0,     0],
       [    0, 18905,     0,     0],
       [    0,     0, 40235,     0],
       [    0,     0,     0,  1764]], dtype=int64)

note: from the confusion matrix that we have no False positive and True nagative 

In [273]:
accu = accuracy_score(pred,y_test)
accu

1.0

the predicted accuracy of the test data is 100% 

#### making a sigmoid prediction of the testing data 

In [284]:
proba_prict = model.predict_proba(X_test,)
proba_prict

array([[4.8771e-07, 7.6088e-06, 9.9999e-01, 1.3603e-06],
       [2.6905e-07, 2.8197e-06, 1.0000e+00, 1.3609e-06],
       [3.5546e-07, 4.3124e-06, 9.9999e-01, 1.1022e-06],
       ...,
       [2.1190e-06, 4.7797e-06, 2.8504e-05, 9.9996e-01],
       [2.8212e-07, 3.5460e-06, 1.0000e+00, 1.1459e-06],
       [7.6093e-07, 9.9999e-01, 9.8131e-06, 1.2088e-06]])

### making test pool

In [286]:
test_pool = Pool(X_test,label=y_test,cat_features=cat_feature)

##### calculating the metric using catboost algorithm and plotting it

In [1]:
metrics  = model.eval_metrics(test_pool,metrics=['Accuracy','AUC'],plot=True)

NameError: name 'model' is not defined

this was what i do to get the idea of number of iterations to use... due to the fact that this process is expensive to calculate..
i terminated the process after getting idea about the parameters to use.

In [253]:
# from sklearn.model_selection import GridSearchCV
# parag_grid = {
#     'learning_rate':np.linspace(1,0.8,3),
#     'depth':[4,5],
#     'iterations':np.linspace(300,500,3,dtype=int),
#     'verbose':[20],
#     use_best_model=True,
#     train_dir='osun_flood'
    
# }
# clf = CatBoostClassifier(cat_features=cat_feature)
# grid_search = GridSearchCV(clf,param_grid=parag_grid,cv=5)
# result = grid_search.fit(X_train,y_train)

# print(result.best_estimator_)
# print(result.best_score_)
# print(result.best_estimator_.get_params_)
# print(result.best_params_)